# Generated by Django 4.1 on 2022-08-05 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('multipageform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JA',
            fields=[
                ('multipagemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='multipageform.multipagemodel')),
                ('first_name', models.CharField(blank=True, max_length=20)),
                ('middle_name', models.CharField(blank=True, max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=20)),
                ('education_level', models.CharField(blank=True, max_length=20)),
                ('year_graduated', models.CharField(blank=True, max_length=4)),
                ('prior_company', models.CharField(blank=True, max_length=20)),
                ('prior_experience', models.TextField(blank=True)),
                ('anything_more', models.BooleanField(default=False)),
                ('personal_statement', models.TextField(blank=True)),
                ('all_is_accurate', models.BooleanField(default=False)),
            ],
            bases=('multipageform.multipagemodel',),
        ),
    ]
